services:
  golang-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-server
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "sqlite3:/app/data.db"

